---
- name: install httpd on servers
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
  - name: restart httpd
    service:
      name: httpd
      state: started